### ISSUE TITLE
NotebookManager is now depreceated in iPython

### ISSUE THREAD

**Issue by m3nu** [laurenceputra/mongo_notebook_manager#4]
This project is very very useful for hosted iPython instances. I also works well on v2, but the NotebookManager class has been replaced by ContentsManager, it [seems](https://github.com/ipython/ipython/blob/7bd04ae4c4c4f246d57f2bdb584ad6e0dbc5b1a5/docs/source/whatsnew/development.rst).

Is it feasible to adapt this to the new interface? I know Mongo quite well, but implemting some of [these functions](https://github.com/ipython/ipython/blob/9a0ef7371060d61415f02526caaa3916a6083d28/IPython/html/services/contents/manager.py) could be a major stretch.

What do you think?

**Comment by m3nu** [comment]
It might be most practical to only use Mongo for the `checkpoint` functions.

**Comment by laurenceputra** [comment]
To add/modify

```
file_exists
get_model
increment_filename
```

To test

```
create_file
copy
```

Existing functions that needs to be tested

```
exists = notebook_exists
save = save_notebook
update = update_notebook
delete = delete_notebook
```

Doesn't seem like alot tbh.

You want to submit a pull request for this? I'm rather busy these couple of weeks

**Comment by m3nu** [comment]
That's true. I'll branch and give it a shot later today.

**Comment by m3nu** [comment]
I ran into a problem because [Tornado](https://github.com/ipython/ipython/blob/9a0ef7371060d61415f02526caaa3916a6083d28/IPython/html/notebook/handlers.py) seems to expect a real file as a notebook? I also want to keep serving CSV, etc from folders. So my usecase would be only for checkpoints, rather than notebooks in Mongo. Maybe there can be a switch to save notebooks to the file system? Is it such a smart idea to mix Mongo and real files?

**Comment by laurenceputra** [comment]
check out stringio?

**Comment by m3nu** [comment]
Yes. My bad. Didn't notice that `file_exists` was a `ContentsManager` method. Back on track.

**Comment by laurenceputra** [comment]
alright. thanks for doing this!

**Comment by m3nu** [comment]
Thanks for starting this.

I'm mostly finished. Basic functionality is working fine. Even together with ordinary files. I'll do some more cleaning up and testing. And change the Mongo code a bit. I had some trouble using authentication. Probably due to pymongo. Authentication there never really worked for me. Only after you authenticate against a collection it works reliably.

**Comment by m3nu** [comment]
It should mostly work, but more testing and some cleanup is still needed. I made a new branch called `ipython3`.

https://github.com/manuelRiel/mongo_notebook_manager/tree/ipython3
